### ISSUE TITLE
Update site metadata

### ISSUE THREAD

**Issue by wonderfulspam** [wonderfulspam/wonderfulspam.github.io#92]
As per `view-source:https://foeg.dk/`:
```html
<meta description='Festival of Endless Gratitude, 20th to 22nd September. Music & art festival in Copenhagen.' />
```
To fix, set proper metadata in `_cobalt.yml`.

**Comment by jespersim** [comment]
Årh ja. Tak!
    Den tirsdag den 4. oktober 2022 kl. 15.48.47 CEST skrev Emil Thorenfeldt ***@***.***>:  
 
 


As per view-source:https://foeg.dk/:
<meta description='Festival of Endless Gratitude, 20th to 22nd September. Music & art festival in Copenhagen.' />
To fix, set proper metadata in _cobalt.yml.
